services:
  - type: web
    name: affilimax
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
